# Generated by Django 4.2.16 on 2024-11-08 00:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
        ('pacientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Documento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Arquivo do Documento')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Assinado', 'Assinado')], default='Pendente', max_length=20)),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='Data de Expiração do Documento')),
                ('hash_documento', models.CharField(blank=True, max_length=256, null=True, verbose_name='Hash do Documento')),
                ('consentimento_informado', models.BooleanField(default=False, verbose_name='Consentimento Informado')),
                ('exigencias_legais', models.TextField(blank=True, null=True, verbose_name='Exigências Legais')),
                ('versao', models.IntegerField(default=1, verbose_name='Versão do Documento')),
                ('compliance_regulamentar', models.TextField(blank=True, null=True, verbose_name='Conformidade Regulamentar')),
                ('associado_prontuario', models.BooleanField(default=False, verbose_name='Associado ao Prontuário')),
                ('analise_automatizada', models.TextField(blank=True, null=True, verbose_name='Análise Automatizada de Risco')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_criados', to='profissionais.profissional')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_assinatura', models.DateTimeField(default=django.utils.timezone.now)),
                ('assinatura_eletronica', models.TextField(blank=True, null=True, verbose_name='Assinatura Eletrônica')),
                ('validade_assinatura', models.DateField(blank=True, null=True, verbose_name='Validade da Assinatura')),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP da Assinatura')),
                ('localizacao_assinatura', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização da Assinatura')),
                ('biometria_hash', models.CharField(blank=True, max_length=256, null=True, verbose_name='Hash da Biometria')),
                ('dupla_autenticacao', models.BooleanField(default=False, verbose_name='Autenticação em Duas Etapas')),
                ('ferramenta_dispositivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ferramenta/Dispositivo Utilizado')),
                ('historico_eventos', models.TextField(blank=True, null=True, verbose_name='Histórico de Eventos')),
                ('assinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_realizadas', to='profissionais.profissional')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='assinaturas.documento')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-data_assinatura'],
            },
        ),
    ]
