# Generated by Django 5.1.2 on 2025-01-06 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica_core', '__first__'),
        ('compras', '0003_pedidofornecedor'),
        ('pacientes', '0002_remove_paciente_convenio_and_more'),
        ('recursos_humanos', '0002_pagamentofuncionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_custo', models.CharField(max_length=100, verbose_name='Centro de Custo')),
                ('periodo_inicio', models.DateField(verbose_name='Início do Período')),
                ('periodo_fim', models.DateField(verbose_name='Fim do Período')),
                ('valor_planejado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Planejado')),
                ('valor_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Gasto')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-periodo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo do Relatório')),
                ('periodo_inicio', models.DateField(verbose_name='Início do Período')),
                ('periodo_fim', models.DateField(verbose_name='Fim do Período')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('conteudo', models.JSONField(verbose_name='Conteúdo do Relatório')),
                ('analise_automatica', models.JSONField(blank=True, null=True, verbose_name='Análise Gerada por IA')),
                ('insights', models.TextField(blank=True, null=True, verbose_name='Insights Automáticos')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='RelatorioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo do Relatório')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('periodo_inicio', models.DateField(verbose_name='Início do Período')),
                ('periodo_fim', models.DateField(verbose_name='Fim do Período')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('conteudo', models.JSONField(verbose_name='Conteúdo do Relatório')),
                ('exportado', models.BooleanField(default=False, verbose_name='Exportado?')),
                ('formato_exportado', models.CharField(blank=True, choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('html', 'HTML')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Relatório Financeiro',
                'verbose_name_plural': 'Relatórios Financeiros',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoCartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operadora', models.CharField(max_length=100, verbose_name='Operadora')),
                ('id_transacao', models.CharField(max_length=255, verbose_name='ID da Transação na Operadora')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_transacao', models.DateTimeField(verbose_name='Data da Transação')),
                ('conciliada', models.BooleanField(default=False, verbose_name='Conciliada?')),
            ],
            options={
                'verbose_name': 'Transação de Cartão de Crédito',
                'verbose_name_plural': 'Transações de Cartão de Crédito',
                'ordering': ['-data_transacao'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Categoria Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoriafinanceira', verbose_name='Subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('pagar', 'A Pagar'), ('receber', 'A Receber')], max_length=50, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('renegociado', 'Renegociado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('parcelada', models.BooleanField(default=False, verbose_name='É Parcelada?')),
                ('numero_parcelas', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('parcela_atual', models.PositiveIntegerField(default=1, verbose_name='Parcela Atual')),
                ('juros', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Juros (%)')),
                ('multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Multa (Valor)')),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto')),
                ('identificador_bancario', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Bancário')),
                ('referencia_externa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência Externa')),
                ('impacto_fluxo_caixa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Impacto no Fluxo de Caixa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('documentos', models.ManyToManyField(blank=True, to='clinica_core.documento', verbose_name='Documentos')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.fornecedor', verbose_name='Fornecedor')),
                ('origem_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.pedidofornecedor', verbose_name='Pedido do Fornecedor')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['-vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('tipo_acao', models.CharField(choices=[('lembrete', 'Lembrete'), ('contato', 'Contato Direto'), ('negociacao', 'Negociação')], max_length=50, verbose_name='Tipo de Ação')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes da Cobrança')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='financeiro.conta')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-data_acao'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('clausulas', models.TextField(blank=True, null=True, verbose_name='Cláusulas do Contrato')),
                ('documentos', models.ManyToManyField(blank=True, to='clinica_core.documento', verbose_name='Documentos Anexados')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255, verbose_name='Ação Realizada')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('detalhes', models.JSONField(blank=True, null=True, verbose_name='Detalhes da Ação')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseSensibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variavel', models.CharField(max_length=100, verbose_name='Variável Analisada')),
                ('variacao_percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Variação (%)')),
                ('impacto_estimado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Impacto Estimado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='financeiro.orcamento')),
            ],
            options={
                'verbose_name': 'Análise de Sensibilidade',
                'verbose_name_plural': 'Análises de Sensibilidade',
            },
        ),
        migrations.CreateModel(
            name='AlertaOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Alerta')),
                ('limite_percentual', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Limite Percentual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='financeiro.orcamento')),
            ],
            options={
                'verbose_name': 'Alerta de Orçamento',
                'verbose_name_plural': 'Alertas de Orçamento',
            },
        ),
        migrations.CreateModel(
            name='RelatorioCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Relatório')),
                ('campos', models.JSONField(verbose_name='Campos Selecionados')),
                ('filtros', models.JSONField(blank=True, null=True, verbose_name='Filtros Aplicados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Relatório Customizado',
                'verbose_name_plural': 'Relatórios Customizados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Renegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_renegociacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Renegociação')),
                ('novo_valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Novo Valor')),
                ('nova_data_vencimento', models.DateField(verbose_name='Nova Data de Vencimento')),
                ('condicoes', models.TextField(blank=True, null=True, verbose_name='Condições Negociadas')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renegociacoes', to='financeiro.conta')),
            ],
            options={
                'verbose_name': 'Renegociação',
                'verbose_name_plural': 'Renegociações',
                'ordering': ['-data_renegociacao'],
            },
        ),
        migrations.CreateModel(
            name='RiscoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score de Risco')),
                ('data_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cálculo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Risco de Crédito',
                'verbose_name_plural': 'Riscos de Crédito',
                'ordering': ['-data_calculo'],
            },
        ),
        migrations.CreateModel(
            name='SimulacaoCenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cenário')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('impacto_receitas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impacto nas Receitas')),
                ('impacto_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impacto nas Despesas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to='financeiro.orcamento')),
            ],
            options={
                'verbose_name': 'Simulação de Cenário',
                'verbose_name_plural': 'Simulações de Cenários',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=50, verbose_name='Tipo')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária'), ('plano_saude', 'Plano de Saúde')], max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da Transação')),
                ('centro_custo', models.CharField(blank=True, max_length=100, verbose_name='Centro de Custo')),
                ('anexos', models.FileField(blank=True, null=True, upload_to='financeiro/anexos/', verbose_name='Anexos')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado')], default='pendente', max_length=20)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('categoria_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_sugeridas', to='financeiro.categoriafinanceira', verbose_name='Categoria Sugerida')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='compras.fornecedor')),
                ('origem_rh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.pagamentofuncionario', verbose_name='Pagamento de Funcionário')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='GatewayPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transacao_gateway', models.CharField(max_length=255, verbose_name='ID da Transação no Gateway')),
                ('tipo_gateway', models.CharField(choices=[('pagseguro', 'PagSeguro'), ('mercado_pago', 'Mercado Pago'), ('paypal', 'PayPal'), ('outros', 'Outros')], max_length=50, verbose_name='Tipo de Gateway')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('falha', 'Falha')], max_length=50, verbose_name='Status do Pagamento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('transacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway', to='financeiro.transacao', verbose_name='Transação')),
            ],
            options={
                'verbose_name': 'Gateway de Pagamento',
                'verbose_name_plural': 'Gateways de Pagamento',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
