# Generated by Django 4.2.16 on 2024-11-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Dispositivo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=100)),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('ultima_comunicacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Comunicação')),
            ],
            options={
                'verbose_name': 'Dispositivo IoT',
                'verbose_name_plural': 'Dispositivos IoT',
            },
        ),
    ]
