# Generated by Django 4.2.16 on 2024-10-19 15:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='assinatura_digital_profissional',
            field=models.CharField(blank=True, help_text='ID da assinatura digital do profissional responsável.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='comorbidades_psiquiatricas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consentimento_familiar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='contato_emergencia',
            field=models.CharField(blank=True, default='Sem contato', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dados_familiares',
            field=models.TextField(blank=True, help_text='Informações sobre histórico familiar de dependência.', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_triagem',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='documentos_digitalizados',
            field=models.JSONField(blank=True, help_text='Armazena links para documentos digitalizados (RG, CPF, plano de saúde).', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='doencas_preexistentes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='etapa_triagem',
            field=models.CharField(choices=[('entrevista_inicial', 'Entrevista Inicial'), ('exames', 'Exames Médicos'), ('analise_risco', 'Análise de Risco')], default='entrevista_inicial', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='evolucao_terapeutica',
            field=models.TextField(blank=True, help_text='Registro detalhado da evolução do paciente durante o tratamento.', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='internacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='leito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos_em_uso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='metas_tratamento',
            field=models.TextField(blank=True, help_text='Metas específicas para o tratamento do paciente.', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='notas_profissionais',
            field=models.TextField(blank=True, help_text='Notas adicionadas pelos profissionais de saúde.', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_cartao_saude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observacoes_internacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='questionarios_periodicos',
            field=models.JSONField(blank=True, help_text='Respostas dos questionários periódicos enviados ao paciente.', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='relatorios_gerados',
            field=models.JSONField(blank=True, help_text='Lista de relatórios gerados automaticamente.', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='responsavel_legal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='resultado_triagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_dependencia',
            field=models.CharField(blank=True, help_text='Ex: álcool, drogas sintéticas.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historico_medico',
            field=models.TextField(blank=True, help_text='Histórico médico detalhado do paciente.', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='InformacaoMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico_medico', models.TextField(help_text='Histórico médico detalhado do paciente.')),
                ('alergias', models.TextField(blank=True, help_text='Alergias que o paciente possui.', null=True)),
                ('medicamentos_em_uso', models.TextField(blank=True, help_text='Medicamentos atualmente em uso pelo paciente.', null=True)),
                ('doencas_preexistentes', models.TextField(blank=True, help_text='Doenças preexistentes do paciente.', null=True)),
                ('tipo_dependencia', models.CharField(blank=True, help_text='Tipo de dependência, como álcool, drogas sintéticas.', max_length=255, null=True)),
                ('comorbidades_psiquiatricas', models.TextField(blank=True, help_text='Comorbidades psiquiátricas do paciente.', null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_medicas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Informação Médica',
                'verbose_name_plural': 'Informações Médicas',
            },
        ),
    ]
