# Generated by Django 4.2.16 on 2024-10-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_options_paciente_alergias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervencaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_intervencao', models.TextField(help_text='Descrição da intervenção sugerida pela IA.')),
                ('tipo_intervencao', models.CharField(choices=[('ajuste_medicamento', 'Ajuste de Medicamento'), ('mudanca_tratamento', 'Mudança de Tratamento'), ('triagem_prioritaria', 'Triagem Prioritária'), ('risco_alto', 'Avaliação de Risco Alto')], max_length=50)),
                ('data_intervencao', models.DateTimeField(auto_now_add=True)),
                ('responsavel_aprovacao', models.CharField(blank=True, help_text='Profissional que aprovou a intervenção.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=50)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervencoes_ia', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Intervenção de IA',
                'verbose_name_plural': 'Intervenções de IA',
            },
        ),
    ]
