# Generated by Django 5.1.2 on 2024-10-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_intervencaoia'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='analise_risco',
            field=models.FloatField(blank=True, help_text='Pontuação de risco gerada automaticamente para o paciente.', null=True),
        ),
    ]
