# Generated by Django 4.2.16 on 2024-11-08 00:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '__first__'),
        ('iot', '0001_initial'),
        ('pacientes', '__first__'),
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField(default=django.utils.timezone.now)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado'), ('Aguardando Documentação', 'Aguardando Documentação'), ('Aguardando Pagamento', 'Aguardando Pagamento')], default='Pendente', max_length=30)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('prescricao', models.TextField(blank=True, null=True)),
                ('tratamento', models.TextField(blank=True, null=True)),
                ('feedback_paciente', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recomendacoes_ia', models.TextField(blank=True, null=True)),
                ('recomendacoes_automaticas', models.TextField(blank=True, null=True)),
                ('avaliacao_risco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('consentimento_paciente', models.BooleanField(default=False)),
                ('documentacao_completa', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento', to='agendamentos.agendamento')),
                ('assinatura_profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_profissionais', to='assinaturas.assinatura')),
                ('autorizacao_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacoes_pacientes', to='assinaturas.assinatura')),
                ('dispositivos_iot', models.ManyToManyField(blank=True, related_name='atendimentos', to='iot.dispositivoiot')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data_atendimento', '-horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('alteracoes', models.TextField()),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='atendimentos.atendimento')),
            ],
            options={
                'verbose_name': 'Auditoria de Atendimento',
                'verbose_name_plural': 'Auditorias de Atendimentos',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
