# Generated by Django 4.2.16 on 2024-11-08 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('prontuarios', '0001_initial'),
        ('profissionais', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='procedimentos',
            field=models.ManyToManyField(blank=True, related_name='atendimentos', to='prontuarios.procedimentorealizado'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='profissionais.profissional'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='transacao_financeira',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento', to='financeiro.transacao'),
        ),
    ]
