# Generated by Django 5.1.2 on 2024-10-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('estado_civil', models.CharField(blank=True, max_length=50, verbose_name='Estado Civil')),
                ('profissao', models.CharField(blank=True, max_length=100, verbose_name='Profissão')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('telefone_fixo', models.CharField(blank=True, max_length=15, verbose_name='Telefone Fixo')),
                ('telefone_celular', models.CharField(max_length=15, verbose_name='Telefone Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('convenio', models.CharField(blank=True, max_length=100, verbose_name='Convênio')),
                ('numero_carteirinha', models.CharField(blank=True, max_length=50, verbose_name='Número da Carteirinha')),
                ('validade_carteirinha', models.DateField(blank=True, null=True, verbose_name='Validade da Carteirinha')),
                ('responsavel_financeiro', models.CharField(blank=True, max_length=255, verbose_name='Responsável Financeiro')),
                ('parentesco_responsavel', models.CharField(blank=True, max_length=50, verbose_name='Parentesco do Responsável')),
                ('cpf_responsavel', models.CharField(blank=True, max_length=14, verbose_name='CPF do Responsável')),
                ('rg_responsavel', models.CharField(blank=True, max_length=20, verbose_name='RG do Responsável')),
                ('telefone_responsavel', models.CharField(blank=True, max_length=15, verbose_name='Telefone do Responsável')),
                ('consentimento_lgpd', models.BooleanField(default=False, verbose_name='Consentimento LGPD')),
                ('data_consentimento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Consentimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('foto', models.ImageField(blank=True, upload_to='fotos_pacientes', verbose_name='Foto')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data da Última Atualização')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
