# Generated by Django 5.1.2 on 2024-12-25 22:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('prontuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cpf_responsavel',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_consentimento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='numero_carteirinha',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='parentesco_responsavel',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='responsavel_financeiro',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='rg_responsavel',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefone_fixo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefone_responsavel',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='validade_carteirinha',
        ),
        migrations.AddField(
            model_name='paciente',
            name='contato_emergencia',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contato de Emergência'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='prontuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_prontuario', to='prontuarios.prontuario'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone_emergencia',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone de Emergência'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone_residencial',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone Residencial'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=255, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=255, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone Celular'),
        ),
    ]
