apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinicaai-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clinicaai
  template:
    metadata:
      labels:
        app: clinicaai
