# Generated by Django 5.1.2 on 2025-01-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=255, verbose_name='Funcionário')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pagamento')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento de Funcionário',
                'verbose_name_plural': 'Pagamentos de Funcionários',
            },
        ),
    ]
