# Generated by Django 4.2.16 on 2024-11-08 00:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '__first__'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_agendamento', models.DateField(verbose_name='Data do Agendamento')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Fim')),
                ('tipo_consulta', models.CharField(choices=[('Consulta Inicial', 'Consulta Inicial'), ('Retorno', 'Retorno'), ('Exame', 'Exame'), ('Teleconsulta', 'Teleconsulta')], default='Consulta Inicial', max_length=50, verbose_name='Tipo de Consulta')),
                ('local_atendimento', models.CharField(choices=[('Presencial', 'Presencial'), ('Telemedicina', 'Telemedicina'), ('Visita Domiciliar', 'Visita Domiciliar')], default='Presencial', max_length=50, verbose_name='Local do Atendimento')),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Cancelado', 'Cancelado'), ('Concluído', 'Concluído')], default='Agendado', max_length=20, verbose_name='Status do Agendamento')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento')),
                ('confirmado_pelo_paciente', models.BooleanField(default=False, verbose_name='Confirmado pelo Paciente')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('sintomas_iniciais', models.TextField(blank=True, verbose_name='Sintomas Iniciais')),
                ('tipo_atendimento', models.CharField(choices=[('Emergencial', 'Emergencial'), ('Rotina', 'Rotina')], default='Rotina', max_length=20, verbose_name='Tipo de Atendimento')),
                ('motivo_consulta', models.CharField(blank=True, max_length=255, verbose_name='Motivo da Consulta')),
                ('meio_pagamento', models.CharField(blank=True, choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Convênio', 'Convênio'), ('Dinheiro', 'Dinheiro'), ('PIX', 'PIX')], max_length=50, verbose_name='Meio de Pagamento')),
                ('status_financeiro', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], default='Pendente', max_length=20, verbose_name='Status Financeiro')),
                ('canal_preferencial', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Email', 'Email')], default='WhatsApp', max_length=20, verbose_name='Canal Preferencial de Notificação')),
                ('lembrete_enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Lembrete Enviado em')),
                ('status_notificacao', models.CharField(choices=[('Enviado', 'Enviado'), ('Lido', 'Lido'), ('Pendente', 'Pendente')], default='Pendente', max_length=20, verbose_name='Status da Notificação')),
                ('equipamentos_necessarios', models.CharField(blank=True, max_length=255, verbose_name='Equipamentos Necessários')),
                ('sala_atendimento', models.CharField(blank=True, max_length=50, verbose_name='Sala de Atendimento')),
                ('dispositivo_iot', models.CharField(blank=True, max_length=100, verbose_name='Dispositivo IoT Necessário')),
                ('probabilidade_cancelamento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Probabilidade de Cancelamento (%)')),
                ('tempo_espera_estimado', models.DurationField(blank=True, null=True, verbose_name='Tempo de Espera Estimado')),
                ('preferencias_paciente', models.CharField(blank=True, max_length=255, verbose_name='Preferências do Paciente')),
                ('confirmar_atendimento_automatico', models.BooleanField(default=False, verbose_name='Confirmar Atendimento Automaticamente')),
                ('log_modificacoes', models.TextField(blank=True, verbose_name='Histórico de Modificações')),
                ('historico_cancelamentos', models.TextField(blank=True, verbose_name='Histórico de Cancelamentos')),
                ('pre_checkin_realizado', models.BooleanField(default=False, verbose_name='Pré-Check-in Realizado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pacientes.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_profissional', to='profissionais.profissional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'unique_together': {('profissional', 'data_agendamento', 'horario_inicio')},
            },
        ),
    ]
