# Generated by Django 4.2.16 on 2024-11-08 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Especialidade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('registro_conselho', models.CharField(max_length=50, unique=True, verbose_name='Registro no Conselho')),
                ('conselho', models.CharField(max_length=100, verbose_name='Conselho de Classe (CRM, CRO, etc.)')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('tipo_contratacao', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica'), ('Freelancer', 'Freelancer')], max_length=50, verbose_name='Tipo de Contratação')),
                ('documentos', models.FileField(blank=True, upload_to='documentos_profissionais/', verbose_name='Documentos')),
                ('horario_atendimento_inicio', models.TimeField(verbose_name='Horário de Início do Atendimento')),
                ('horario_atendimento_fim', models.TimeField(verbose_name='Horário de Fim do Atendimento')),
                ('dias_atendimento', models.CharField(max_length=50, verbose_name='Dias da Semana para Atendimento')),
                ('especialidades', models.ManyToManyField(related_name='profissionais', to='profissionais.especialidade', verbose_name='Especialidades')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='RegistroHorasTrabalhadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dia')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Horas Trabalhadas')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_trabalhadas', to='profissionais.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Registro de Horas Trabalhadas',
                'verbose_name_plural': 'Registros de Horas Trabalhadas',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dia da Disponibilidade')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Fim')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='profissionais.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Disponibilidade',
                'verbose_name_plural': 'Disponibilidades',
                'unique_together': {('profissional', 'dia', 'horario_inicio', 'horario_fim')},
            },
        ),
    ]
