# Generated by Django 5.1.2 on 2024-11-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('especialidade', models.CharField(max_length=100)),
                ('registro_profissional', models.CharField(max_length=50)),
                ('contato', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
